# Generated by Django 4.2.5 on 2024-03-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
