# Generated by Django 4.2.5 on 2024-03-08 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_track', '0002_alter_track_time_end_alter_track_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 8, 23, 59), null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 15, 4, 29, 387539)),
        ),
    ]
